# working directory
twister2.resource.scheduler.mpi.working.directory: "${HOME}/.twister2/jobs"

# the launcher class
twister2.class.launcher: "edu.iu.dsc.tws.rsched.schedulers.nomad.NomadLauncher"

# The URI of Nomad API
twister2.nomad.scheduler.uri: "http://149.165.150.81:4646"

# The nomad schedules cpu resources in terms of clock frequency (e.g. MHz), while Heron topologies
# specify cpu requests in term of cores.  This config maps core to clock freqency.
twister2.nomad.core.freq.mapping: 2000


# weather we are in a shared file system, if that is the case, each worker will not download the
# core package and job package, otherwise they will download those packages
twister2.filesystem.shared: true

# name of the script
twister2.nomad.shell.script: "nomad.sh"

# path to the system core package
twister2.system.package.uri: "${TWISTER2_DIST}/twister2-core-0.2.1.tar.gz"
